-- Stores Table
CREATE TABLE stores (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_code VARCHAR2(40) NOT NULL UNIQUE,
  name VARCHAR2(100) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Terminals Table
CREATE TABLE terminals (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  terminal_code VARCHAR2(40) NOT NULL UNIQUE,
  store_id NUMBER NOT NULL,
  status VARCHAR2(20) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_terminal_store FOREIGN KEY (store_id) REFERENCES stores(id)
);

-- Payment Transactions Table
CREATE TABLE payment_transactions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_id VARCHAR2(60) NOT NULL UNIQUE,
  store_id NUMBER NOT NULL,
  terminal_id NUMBER,
  amount NUMBER(19) NOT NULL,
  currency VARCHAR2(10) NOT NULL,
  method VARCHAR2(20) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  buyer_id VARCHAR2(60),
  description VARCHAR2(200),
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
  approved_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_tx_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_tx_terminal FOREIGN KEY (terminal_id) REFERENCES terminals(id)
);

-- Indexes
CREATE INDEX idx_tx_requested_at ON payment_transactions(requested_at DESC);
CREATE INDEX idx_tx_store_status ON payment_transactions(store_id, status);
CREATE INDEX idx_tx_method ON payment_transactions(method);